spring:
  application:
    name: example-ayaka
  ai:
    openai:
      chat:
        enabled: true
        api-key: ${SPRING_AI_OPENAI_API_KEY}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen-max
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
    database-platform: org.hibernate.community.dialect.SQLiteDialect

# ayaka setup
ayaka:
  plugin:
    plugin-packages:
      - io.github.qingshu.ayaka.example
  http:
    enable: true
    api-port: 5800
    endpoint: /ayaka
    secret: U1FfRzMxQkVvRjBBZ0g5N25tS3Z1YlR3T1NTd0xHNk0=