spring:
  application:
    name: example-ayaka
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  ai:
    openai:
      chat:
        enabled: true
        api-key: ${SPRING_AI_OPENAI_API_KEY}
        base-url: https://dashscope.aliyuncs.com/compatible-mode
        options:
          model: qwen-max

# ayaka setup
ayaka:
  plugin:
    plugin-packages:
      - io.github.qingshu.ayaka.example
  http:
    enable: true
    api-port: 5800
    endpoint: /ayaka
    secret: U1FfRzMxQkVvRjBBZ0g5N25tS3Z1YlR3T1NTd0xHNk0=