spring:
  application:
    name: example-ayaka
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# ayaka setup
ayaka:
  ws:
    server:
      enable: false
      url: "/ws/ayaka"
    client:
      enable: true
      url: "ws://127.0.0.1:5800"
  task:
    thread-name-prefix: "ayaka-async-task"
  plugin:
    plugin-package: "io.github.qingshu.ayaka.example"

# log setup
logging:
  level:
    root: INFO
    io.github.qingshu.ayaka.example: DEBUG
  file:
    name: logs/run.log
