name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set executable permissions for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle Wrapper
        run: ./gradlew clean build
        env:
          GITHUB_ACTOR: ${{secrets.MY_GITHUB_ACTOR}}
          GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}

      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: example-ayaka-artifact
          path: build/libs/example-ayaka-*.*.*-SNAPSHOT.jar

  download:
    runs-on: ubuntu-latest
    needs: build

    steps:

      - name: Download JAR artifact
        uses: actions/download-artifact@v4
        with:
          name: example-ayaka-artifact

      - name: SCP Files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: example-ayaka-artifact
          target: ${{secrets.SSH_WORK_PATH}}

      - name: Start project
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
          ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.SSH_WORK_PATH }} \
          && cd .. && ./restart.sh"
