name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set executable permissions for gradlew
      run: chmod +x ./gradlew

    - name: Build with Gradle Wrapper
      run: ./gradlew clean build
      env:
        GITHUB_ACTOR: ${{secrets.MY_GITHUB_ACTOR}}
        GITHUB_TOKEN: ${{secrets.MY_GITHUB_TOKEN}}

    - name: SCP Files
      run: |
        scp -o StrictHostKeyChecking=no -P ${{ secrets.SSH_PORT }} \
        build/libs/example-ayaka-*.*.*.jar \
        ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/root/qqBot/ayaka-server/

    - name: Restart remote service
      run: |
        ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
        ${{ secrets.USERNAME }}@${{ secrets.HOST }} "cd /root/qqBot/ayaka-server && screen -S client -X quit && screen -dmS client ./run.sh"

            
          
